import { palette } from '../palette';
import {
  sharedInteractiveTokens,
  sharedPaletteTokens,
  sharedTextTokens,
  sharedTheme,
} from './sharedTheme';
import type { SemanticTokens } from './types';

export const darkTheme: SemanticTokens = {
  ...sharedTheme,
  surface: {
    background: palette.neutral650,
    surfacePrimary: palette.blue900,
    surfaceSecondary: palette.gray800,
    surfaceTertiary: palette.neutral750,
    overlay: 'rgba(0, 0, 0, 0.8)',
    disabled: palette.neutral800,
  },
  text: {
    ...sharedTextTokens,
    primary: palette.neutral100,
    secondary: palette.neutral200,
    tertiary: palette.neutral350,
    disabled: palette.neutral500,
  },
  interactive: {
    ...sharedInteractiveTokens,
    accentHover: palette.pink500,
    accentActive: palette.pink400,
    accentLight: palette.pink900,
    secondaryHover: palette.blue400,
    border: palette.neutral700,
    inputBorder: palette.neutral750,
  },
  shadows: {
    sm: {
      elevation: 2,
      shadowColor: palette.black,
      shadowOpacity: 0.2,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
    },
    md: {
      elevation: 3,
      shadowColor: palette.black,
      shadowOpacity: 0.3,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
    },
    lg: {
      elevation: 5,
      shadowColor: palette.black,
      shadowOpacity: 0.4,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
    },
    xl: {
      elevation: 8,
      shadowColor: palette.black,
      shadowOpacity: 0.5,
      shadowRadius: 28,
      shadowOffset: { width: 0, height: 14 },
    },
  },
  backgroundLight: palette.neutral800,
  surfaceDefault: palette.neutral900,
  surfaceSecondary: palette.neutral800,
  cardBackground: palette.neutral800,
  cardBorder: palette.neutral700,
  textPrimary: palette.neutral100,
  textSecondary: palette.neutral200,
  textTertiary: palette.neutral350,
  textOnAccent: sharedPaletteTokens.textOnAccent,
  borderDefault: palette.neutral700,
  accent: sharedPaletteTokens.accent,
  accentHover: palette.pink500,
  accentLight: palette.pink900,
  inputBackground: palette.neutral850,
  inputBorder: palette.neutral750,
  inputPlaceholder: palette.neutral450,
  success: sharedPaletteTokens.success,
  warning: sharedPaletteTokens.warning,
  danger: sharedPaletteTokens.danger,
  bodyText: palette.neutral200,
  secondaryText: palette.neutral350,
  softAccent: palette.pink900,
  muted: palette.neutral450,
  white: palette.neutral100,
  overlay: 'rgba(0, 0, 0, 0.8)',
  primary: sharedPaletteTokens.primary,
};
