import { palette } from '../palette';
import {
    sharedInteractiveTokens,
    sharedPaletteTokens,
    sharedTextTokens,
    sharedTheme,
} from './sharedTheme';
import type { SemanticTokens } from './types';

export const darkTheme: SemanticTokens = {
  ...sharedTheme,
  surface: {
    background: palette.neutral650,
    surfacePrimary: palette.neutral650,
    surfaceSecondary: palette.gray800,
    surfaceTertiary: palette.neutral750,
    overlay: 'rgba(0, 0, 0, 0.8)',
    disabled: palette.neutral800,
  },
  text: {
    ...sharedTextTokens,
    primary: palette.neutral100,
    secondary: palette.neutral200,
    tertiary: palette.neutral350,
    disabled: palette.neutral500,
  },
  interactive: {
    ...sharedInteractiveTokens,
    accentHover: palette.blue400,
    accentActive: palette.blue400,
    accentLight: palette.blue400,
    secondaryHover: palette.blue400,
    border: palette.neutral700,
    inputBorder: palette.neutral750,
  },
  // geometric shadow specs moved to foundation; theme exposes shadowColor
  shadowColor: palette.black,
  backgroundLight: palette.neutral800,
  surfaceDefault: palette.neutral900,
  surfaceSecondary: palette.neutral800,
  cardBackground: palette.neutral800,
  cardBorder: palette.neutral700,
  textPrimary: palette.neutral100,
  textSecondary: palette.neutral200,
  textTertiary: palette.neutral350,
  textOnAccent: sharedPaletteTokens.textOnAccent,
  borderDefault: palette.neutral700,
  accent: sharedPaletteTokens.accent,
  accentHover: palette.pink500,
  accentLight: palette.pink900,
  inputBackground: palette.neutral850,
  inputBorder: palette.neutral750,
  inputPlaceholder: palette.neutral450,
  success: sharedPaletteTokens.success,
  warning: sharedPaletteTokens.warning,
  danger: sharedPaletteTokens.danger,
  bodyText: palette.neutral200,
  secondaryText: palette.neutral350,
  softAccent: palette.pink900,
  muted: palette.neutral450,
  white: palette.neutral100,
  overlay: 'rgba(0, 0, 0, 0.8)',
  primary: sharedPaletteTokens.primary,
};
