import { palette } from '../palette';
import {
    sharedInteractiveTokens,
    sharedPaletteTokens,
    sharedTextTokens,
    sharedTheme,
} from './sharedTheme';
import type { SemanticTokens } from './types';

export const lightTheme: SemanticTokens = {
  ...sharedTheme,
  surface: {
    background: palette.neutral50,
    surfacePrimary: palette.white,
    surfaceSecondary: palette.neutral200,
    surfaceTertiary: palette.neutral300,
    overlay: 'rgba(30, 23, 20, 0.4)',
    disabled: palette.neutral200,
  },
  text: {
    ...sharedTextTokens,
    primary: palette.neutral700,
    secondary: palette.neutral600,
    tertiary: palette.neutral500,
    disabled: palette.neutral400,
  },
  interactive: {
    ...sharedInteractiveTokens,
    accentHover: palette.pink700,
    accentActive: palette.pink800,
    accentLight: palette.pink100,
    secondaryHover: palette.blue600,
    border: palette.neutral400,
    inputBorder: palette.neutral350,
  },
  shadows: {
    sm: {
      elevation: 2,
      shadowColor: palette.neutral700,
      shadowOpacity: 0.05,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
    },
    md: {
      elevation: 3,
      shadowColor: palette.neutral700,
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
    },
    lg: {
      elevation: 5,
      shadowColor: palette.neutral700,
      shadowOpacity: 0.12,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
    },
    xl: {
      elevation: 8,
      shadowColor: palette.neutral700,
      shadowOpacity: 0.15,
      shadowRadius: 28,
      shadowOffset: { width: 0, height: 14 },
    },
  },
  backgroundLight: palette.neutral50,
  surfaceDefault: palette.white,
  surfaceSecondary: palette.neutral200,
  cardBackground: palette.neutral300,
  cardBorder: palette.neutral400,
  textPrimary: palette.neutral700,
  textSecondary: palette.neutral600,
  textTertiary: palette.neutral500,
  textOnAccent: sharedPaletteTokens.textOnAccent,
  borderDefault: palette.neutral400,
  accent: sharedPaletteTokens.accent,
  accentHover: palette.pink700,
  accentLight: palette.pink100,
  inputBackground: palette.neutral50,
  inputBorder: palette.neutral350,
  inputPlaceholder: palette.neutral500,
  success: sharedPaletteTokens.success,
  warning: sharedPaletteTokens.warning,
  danger: sharedPaletteTokens.danger,
  bodyText: palette.neutral600,
  secondaryText: palette.neutral500,
  softAccent: palette.pink100,
  muted: palette.neutral500,
  white: palette.white,
  overlay: 'rgba(30, 23, 20, 0.4)',
  primary: sharedPaletteTokens.primary,
};
